---
- name: install httpd
  yum:
    name: httpd
    update_cache: true
    state: "{{ apache_package_state }}"
  become: true

- name: ensure httpd is enabled and running
  service:
    name: httpd
    state: "{{ apache_state }}"
    enabled: "{{ apache_enabled }}"
  become: true

- name: copy /var/www/html/index.html
  template:
    src: templates/index.html.j2
    dest: /var/www/html/index.html
    mode: 0755
  become: true
  notify: restart apache

- name: ensure firewalld is installed
  yum:
    name: firewalld
    update_cache: true
    state: "{{ firewalld_package_state }}"
  become: true

- name: ensure firewalld is enabled and running
  service:
    name: firewalld
    state: "{{ firewalld_state }}"
    enabled: "{{ firewalld_enabled }}"
  become: true

- name: permit traffic for ssh service
  firewalld:
    service: ssh
    state: enabled
    permanent: true
    immediate: true
  become: true
  notify: reload firewalld

- name: permit traffic for http service
  firewalld:
    port: "{{ apache_listen_port }}/tcp"
    state: enabled
    permanent: true
    immediate: true
  become: true
  notify: reload firewalld
